---
archetypedir:               "archetype"
# hostname (and path) to the root, e.g. http://spf13.com/
baseURL:                    "http://crazymole.github.io/"
# language
languageCode = "en-us"
# include content marked as draft
buildDrafts:                false
# include content with publishdate in the future
buildFuture:                false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs:               false
canonifyURLs:               false
# config file (default is path/config.yaml|json|toml)
config:                     "config.toml"
contentdir:                 "content"
dataDir:                    "data"
defaultExtension:           "html"
defaultLayout:              "post"
disableLiveReload:          false
# Do not build RSS files
disableRSS:                 false
# Do not build Sitemap file
disableSitemap:             false
# edit new content with this editor, if provided
editor:                     "George Zhang"
footnoteAnchorPrefix:       ""
footnoteReturnLinkContents: ""
languageCode:               ""
layoutdir:                  "layouts"
# Enable Logging
log:                        false
# Log File path (if set, logging enabled automatically)
logFile:                    ""
# "yaml", "toml", "json"
metaDataFormat:             "toml"
newContentEditor:           ""
# Don't sync modification time of files
noTimes:                    false
paginate:                   10
paginatePath:               "page"
permalinks:
# Pluralize titles in lists using inflect
pluralizeListTitles:        true
# Preserve special characters in taxonomy names ("GÃ©rard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames:      false
# filesystem path to write files to
publishdir:                 "public"
# color-codes for highlighting derived from this style
pygmentsStyle:              "monokai"
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses:         false
# default sitemap configuration map
sitemap:
# filesystem path to read files relative from
source:                     ""
staticdir:                  "static"
# display memory and timing of different steps of the program
stepAnalysis:               false
# theme to use (located in /themes/THEMENAME/)
theme:                      ""
title:                      "George's playground"
# if true, use /filename.html instead of /filename/
uglyURLs:                   false
# Do not make the url/path to lowercase
disablePathToLower:         false
# if true, auto-detect Chinese/Janapese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage              false
# verbose output
verbose:                    false
# verbose logging
verboseLog:                 false
# watch filesystem for changes and recreate as needed
watch:                      true
---
